server.port = 9090
 #spring.data.mongodb.uri= mongodb+srv://root:7SFGz7co3s8LZWhW@cluster0.wnwoa.mongodb.net/timesheet-management?retryWrites=true&w=majority
 spring.data.mongodb.uri= mongodb+srv://root:7SFGz7co3s8LZWhW@cluster0.soegy.mongodb.net/timesheet-management
 
 #7SFGz7co3s8LZWhW